[package]
name = "psobench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
nalgebra = { version = "0.29", features = ["serde"]}
indicatif = "0.16"
serde_json = "1.0"